/*
 * Wheel Fitment API
 * The Wheel Fitment API allows for programmatic access to the database of www.wheel-size.com and its services. Use this API to retrieve information about vehicle fitment database for rims and tires, including OE and option fitments, and plus/minus sizing fitment information. A variety of country and language specific options are available. The coverage of fitment data for vehicles manufactured since 2000 is nearly 100%.  The information about fitment data is updated on a daily basis.
 *
 * OpenAPI spec version: v1
 * Contact: info@wheel-size.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.wheelsize.api.client.api;

import com.wheelsize.api.client.ApiCallback;
import com.wheelsize.api.client.ApiClient;
import com.wheelsize.api.client.ApiException;
import com.wheelsize.api.client.ApiResponse;
import com.wheelsize.api.client.Configuration;
import com.wheelsize.api.client.Pair;
import com.wheelsize.api.client.ProgressRequestBody;
import com.wheelsize.api.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import java.math.BigDecimal;
import com.wheelsize.api.client.model.BoltPattern;
import com.wheelsize.api.client.model.MakeWithModels;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class BoltPatternsApi {
    private ApiClient apiClient;

    public BoltPatternsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public BoltPatternsApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /**
     * Build call for boltPatternsList
     * @param stud Number of stud holes (e.g. &#x60;5&#x60;) (optional)
     * @param studMin Lower bound for number of stud holes (e.g. &#x60;4&#x60;) (optional)
     * @param studMax Upper bound for number of stud holes (e.g. &#x60;7&#x60;) (optional)
     * @param pcd Pitch circle diameter, mm (e.g. &#x60;115&#x60;) (optional)
     * @param pcdMin Lower bound for pitch circle diameter, mm (e.g. &#x60;105&#x60;) (optional)
     * @param pcdMax Upper bound for pitch circle diameter, mm (e.g. &#x60;135&#x60;) (optional)
     * @param brands Show information only for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;mitsubishi,nissan,toyota&#x60;) (optional)
     * @param brandsExclude Don&#39;t show information for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;geely,great-wall&#x60;) (optional)
     * @param countries Show information for local manufacturers from specified countries only. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;us,gb,jp&#x60;) (optional)
     * @param countriesExclude Don&#39;t show information for local manufacturers from specified countries. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;ru,ua&#x60;) (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call boltPatternsListCall(BigDecimal stud, BigDecimal studMin, BigDecimal studMax, BigDecimal pcd, BigDecimal pcdMin, BigDecimal pcdMax, String brands, String brandsExclude, String countries, String countriesExclude, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/bolt-patterns/";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (stud != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("stud", stud));
        if (studMin != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("stud_min", studMin));
        if (studMax != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("stud_max", studMax));
        if (pcd != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("pcd", pcd));
        if (pcdMin != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("pcd_min", pcdMin));
        if (pcdMax != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("pcd_max", pcdMax));
        if (brands != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("brands", brands));
        if (brandsExclude != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("brands_exclude", brandsExclude));
        if (countries != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("countries", countries));
        if (countriesExclude != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("countries_exclude", countriesExclude));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "user_key" };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call boltPatternsListValidateBeforeCall(BigDecimal stud, BigDecimal studMin, BigDecimal studMax, BigDecimal pcd, BigDecimal pcdMin, BigDecimal pcdMax, String brands, String brandsExclude, String countries, String countriesExclude, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        

        com.squareup.okhttp.Call call = boltPatternsListCall(stud, studMin, studMax, pcd, pcdMin, pcdMax, brands, brandsExclude, countries, countriesExclude, progressListener, progressRequestListener);
        return call;

    }

    /**
     * Get list of bolt patterns
     * A list of possible bolt patterns with the number of matching model modifications
     * @param stud Number of stud holes (e.g. &#x60;5&#x60;) (optional)
     * @param studMin Lower bound for number of stud holes (e.g. &#x60;4&#x60;) (optional)
     * @param studMax Upper bound for number of stud holes (e.g. &#x60;7&#x60;) (optional)
     * @param pcd Pitch circle diameter, mm (e.g. &#x60;115&#x60;) (optional)
     * @param pcdMin Lower bound for pitch circle diameter, mm (e.g. &#x60;105&#x60;) (optional)
     * @param pcdMax Upper bound for pitch circle diameter, mm (e.g. &#x60;135&#x60;) (optional)
     * @param brands Show information only for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;mitsubishi,nissan,toyota&#x60;) (optional)
     * @param brandsExclude Don&#39;t show information for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;geely,great-wall&#x60;) (optional)
     * @param countries Show information for local manufacturers from specified countries only. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;us,gb,jp&#x60;) (optional)
     * @param countriesExclude Don&#39;t show information for local manufacturers from specified countries. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;ru,ua&#x60;) (optional)
     * @return List&lt;BoltPattern&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public List<BoltPattern> boltPatternsList(BigDecimal stud, BigDecimal studMin, BigDecimal studMax, BigDecimal pcd, BigDecimal pcdMin, BigDecimal pcdMax, String brands, String brandsExclude, String countries, String countriesExclude) throws ApiException {
        ApiResponse<List<BoltPattern>> resp = boltPatternsListWithHttpInfo(stud, studMin, studMax, pcd, pcdMin, pcdMax, brands, brandsExclude, countries, countriesExclude);
        return resp.getData();
    }

    /**
     * Get list of bolt patterns
     * A list of possible bolt patterns with the number of matching model modifications
     * @param stud Number of stud holes (e.g. &#x60;5&#x60;) (optional)
     * @param studMin Lower bound for number of stud holes (e.g. &#x60;4&#x60;) (optional)
     * @param studMax Upper bound for number of stud holes (e.g. &#x60;7&#x60;) (optional)
     * @param pcd Pitch circle diameter, mm (e.g. &#x60;115&#x60;) (optional)
     * @param pcdMin Lower bound for pitch circle diameter, mm (e.g. &#x60;105&#x60;) (optional)
     * @param pcdMax Upper bound for pitch circle diameter, mm (e.g. &#x60;135&#x60;) (optional)
     * @param brands Show information only for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;mitsubishi,nissan,toyota&#x60;) (optional)
     * @param brandsExclude Don&#39;t show information for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;geely,great-wall&#x60;) (optional)
     * @param countries Show information for local manufacturers from specified countries only. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;us,gb,jp&#x60;) (optional)
     * @param countriesExclude Don&#39;t show information for local manufacturers from specified countries. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;ru,ua&#x60;) (optional)
     * @return ApiResponse&lt;List&lt;BoltPattern&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<List<BoltPattern>> boltPatternsListWithHttpInfo(BigDecimal stud, BigDecimal studMin, BigDecimal studMax, BigDecimal pcd, BigDecimal pcdMin, BigDecimal pcdMax, String brands, String brandsExclude, String countries, String countriesExclude) throws ApiException {
        com.squareup.okhttp.Call call = boltPatternsListValidateBeforeCall(stud, studMin, studMax, pcd, pcdMin, pcdMax, brands, brandsExclude, countries, countriesExclude, null, null);
        Type localVarReturnType = new TypeToken<List<BoltPattern>>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Get list of bolt patterns (asynchronously)
     * A list of possible bolt patterns with the number of matching model modifications
     * @param stud Number of stud holes (e.g. &#x60;5&#x60;) (optional)
     * @param studMin Lower bound for number of stud holes (e.g. &#x60;4&#x60;) (optional)
     * @param studMax Upper bound for number of stud holes (e.g. &#x60;7&#x60;) (optional)
     * @param pcd Pitch circle diameter, mm (e.g. &#x60;115&#x60;) (optional)
     * @param pcdMin Lower bound for pitch circle diameter, mm (e.g. &#x60;105&#x60;) (optional)
     * @param pcdMax Upper bound for pitch circle diameter, mm (e.g. &#x60;135&#x60;) (optional)
     * @param brands Show information only for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;mitsubishi,nissan,toyota&#x60;) (optional)
     * @param brandsExclude Don&#39;t show information for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;geely,great-wall&#x60;) (optional)
     * @param countries Show information for local manufacturers from specified countries only. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;us,gb,jp&#x60;) (optional)
     * @param countriesExclude Don&#39;t show information for local manufacturers from specified countries. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;ru,ua&#x60;) (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call boltPatternsListAsync(BigDecimal stud, BigDecimal studMin, BigDecimal studMax, BigDecimal pcd, BigDecimal pcdMin, BigDecimal pcdMax, String brands, String brandsExclude, String countries, String countriesExclude, final ApiCallback<List<BoltPattern>> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = boltPatternsListValidateBeforeCall(stud, studMin, studMax, pcd, pcdMin, pcdMax, brands, brandsExclude, countries, countriesExclude, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<List<BoltPattern>>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for boltPatternsRead
     * @param boltPattern Bolt pattern combines number of stud holes and pitch circle diameter. Use _**&#x60;GET /bolt-patterns/&#x60;**_ to get possible values (e.g. &#x60;5x105&#x60;) (required)
     * @param rimDiameter Rim diameter, in (e.g. &#x60;16&#x60;) (optional)
     * @param rimWidth Rim width, in (e.g. &#x60;7&#x60;) (optional)
     * @param offset Rim offset, mm (e.g. &#x60;40&#x60;) (optional)
     * @param offsetMin Lower bound for rim offset, mm (e.g. &#x60;35&#x60;) (optional)
     * @param offsetMax Upper bound for rim offset, mm (e.g. &#x60;45&#x60;) (optional)
     * @param cb Centre bore value, mm (e.g. &#x60;60&#x60;) (optional)
     * @param cbMin Lower bound for centre bore value, mm (e.g. &#x60;55&#x60;) (optional)
     * @param cbMax Upper bound for centre bore value, mm (e.g. &#x60;65&#x60;) (optional)
     * @param lang Use this parameter anywhere in the API to get *&#x60;name&#x60;* field translation of the following objects: **&#x60;Make&#x60;**, **&#x60;Model&#x60;**, **&#x60;Market&#x60;**. Across the *&#x60;name&#x60;* this objects will have *&#x60;name_en&#x60;* field with original english name. By default &#x60;en&#x60; language is used.  Available languages: &#x60;en,de,ru,es,pt,fr,ja,zh-cn&#x60;. Currently translation works for chinese &#x60;zh-cn&#x60; language only (optional)
     * @param brands Show information only for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;mitsubishi,nissan,toyota&#x60;) (optional)
     * @param brandsExclude Don&#39;t show information for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;geely,great-wall&#x60;) (optional)
     * @param countries Show information for local manufacturers from specified countries only. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;us,gb,jp&#x60;) (optional)
     * @param countriesExclude Don&#39;t show information for local manufacturers from specified countries. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;ru,ua&#x60;) (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call boltPatternsReadCall(String boltPattern, BigDecimal rimDiameter, BigDecimal rimWidth, BigDecimal offset, BigDecimal offsetMin, BigDecimal offsetMax, BigDecimal cb, BigDecimal cbMin, BigDecimal cbMax, String lang, String brands, String brandsExclude, String countries, String countriesExclude, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/bolt-patterns/{bolt_pattern}/"
            .replaceAll("\\{" + "bolt_pattern" + "\\}", apiClient.escapeString(boltPattern.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (rimDiameter != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("rim_diameter", rimDiameter));
        if (rimWidth != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("rim_width", rimWidth));
        if (offset != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("offset", offset));
        if (offsetMin != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("offset_min", offsetMin));
        if (offsetMax != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("offset_max", offsetMax));
        if (cb != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("cb", cb));
        if (cbMin != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("cb_min", cbMin));
        if (cbMax != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("cb_max", cbMax));
        if (lang != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("lang", lang));
        if (brands != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("brands", brands));
        if (brandsExclude != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("brands_exclude", brandsExclude));
        if (countries != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("countries", countries));
        if (countriesExclude != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("countries_exclude", countriesExclude));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "user_key" };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call boltPatternsReadValidateBeforeCall(String boltPattern, BigDecimal rimDiameter, BigDecimal rimWidth, BigDecimal offset, BigDecimal offsetMin, BigDecimal offsetMax, BigDecimal cb, BigDecimal cbMin, BigDecimal cbMax, String lang, String brands, String brandsExclude, String countries, String countriesExclude, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'boltPattern' is set
        if (boltPattern == null) {
            throw new ApiException("Missing the required parameter 'boltPattern' when calling boltPatternsRead(Async)");
        }
        

        com.squareup.okhttp.Call call = boltPatternsReadCall(boltPattern, rimDiameter, rimWidth, offset, offsetMin, offsetMax, cb, cbMin, cbMax, lang, brands, brandsExclude, countries, countriesExclude, progressListener, progressRequestListener);
        return call;

    }

    /**
     * Model modifications by bolt pattern
     * Get a list of model modifications matching to the given bolt pattern
     * @param boltPattern Bolt pattern combines number of stud holes and pitch circle diameter. Use _**&#x60;GET /bolt-patterns/&#x60;**_ to get possible values (e.g. &#x60;5x105&#x60;) (required)
     * @param rimDiameter Rim diameter, in (e.g. &#x60;16&#x60;) (optional)
     * @param rimWidth Rim width, in (e.g. &#x60;7&#x60;) (optional)
     * @param offset Rim offset, mm (e.g. &#x60;40&#x60;) (optional)
     * @param offsetMin Lower bound for rim offset, mm (e.g. &#x60;35&#x60;) (optional)
     * @param offsetMax Upper bound for rim offset, mm (e.g. &#x60;45&#x60;) (optional)
     * @param cb Centre bore value, mm (e.g. &#x60;60&#x60;) (optional)
     * @param cbMin Lower bound for centre bore value, mm (e.g. &#x60;55&#x60;) (optional)
     * @param cbMax Upper bound for centre bore value, mm (e.g. &#x60;65&#x60;) (optional)
     * @param lang Use this parameter anywhere in the API to get *&#x60;name&#x60;* field translation of the following objects: **&#x60;Make&#x60;**, **&#x60;Model&#x60;**, **&#x60;Market&#x60;**. Across the *&#x60;name&#x60;* this objects will have *&#x60;name_en&#x60;* field with original english name. By default &#x60;en&#x60; language is used.  Available languages: &#x60;en,de,ru,es,pt,fr,ja,zh-cn&#x60;. Currently translation works for chinese &#x60;zh-cn&#x60; language only (optional)
     * @param brands Show information only for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;mitsubishi,nissan,toyota&#x60;) (optional)
     * @param brandsExclude Don&#39;t show information for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;geely,great-wall&#x60;) (optional)
     * @param countries Show information for local manufacturers from specified countries only. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;us,gb,jp&#x60;) (optional)
     * @param countriesExclude Don&#39;t show information for local manufacturers from specified countries. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;ru,ua&#x60;) (optional)
     * @return List&lt;MakeWithModels&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public List<MakeWithModels> boltPatternsRead(String boltPattern, BigDecimal rimDiameter, BigDecimal rimWidth, BigDecimal offset, BigDecimal offsetMin, BigDecimal offsetMax, BigDecimal cb, BigDecimal cbMin, BigDecimal cbMax, String lang, String brands, String brandsExclude, String countries, String countriesExclude) throws ApiException {
        ApiResponse<List<MakeWithModels>> resp = boltPatternsReadWithHttpInfo(boltPattern, rimDiameter, rimWidth, offset, offsetMin, offsetMax, cb, cbMin, cbMax, lang, brands, brandsExclude, countries, countriesExclude);
        return resp.getData();
    }

    /**
     * Model modifications by bolt pattern
     * Get a list of model modifications matching to the given bolt pattern
     * @param boltPattern Bolt pattern combines number of stud holes and pitch circle diameter. Use _**&#x60;GET /bolt-patterns/&#x60;**_ to get possible values (e.g. &#x60;5x105&#x60;) (required)
     * @param rimDiameter Rim diameter, in (e.g. &#x60;16&#x60;) (optional)
     * @param rimWidth Rim width, in (e.g. &#x60;7&#x60;) (optional)
     * @param offset Rim offset, mm (e.g. &#x60;40&#x60;) (optional)
     * @param offsetMin Lower bound for rim offset, mm (e.g. &#x60;35&#x60;) (optional)
     * @param offsetMax Upper bound for rim offset, mm (e.g. &#x60;45&#x60;) (optional)
     * @param cb Centre bore value, mm (e.g. &#x60;60&#x60;) (optional)
     * @param cbMin Lower bound for centre bore value, mm (e.g. &#x60;55&#x60;) (optional)
     * @param cbMax Upper bound for centre bore value, mm (e.g. &#x60;65&#x60;) (optional)
     * @param lang Use this parameter anywhere in the API to get *&#x60;name&#x60;* field translation of the following objects: **&#x60;Make&#x60;**, **&#x60;Model&#x60;**, **&#x60;Market&#x60;**. Across the *&#x60;name&#x60;* this objects will have *&#x60;name_en&#x60;* field with original english name. By default &#x60;en&#x60; language is used.  Available languages: &#x60;en,de,ru,es,pt,fr,ja,zh-cn&#x60;. Currently translation works for chinese &#x60;zh-cn&#x60; language only (optional)
     * @param brands Show information only for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;mitsubishi,nissan,toyota&#x60;) (optional)
     * @param brandsExclude Don&#39;t show information for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;geely,great-wall&#x60;) (optional)
     * @param countries Show information for local manufacturers from specified countries only. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;us,gb,jp&#x60;) (optional)
     * @param countriesExclude Don&#39;t show information for local manufacturers from specified countries. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;ru,ua&#x60;) (optional)
     * @return ApiResponse&lt;List&lt;MakeWithModels&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<List<MakeWithModels>> boltPatternsReadWithHttpInfo(String boltPattern, BigDecimal rimDiameter, BigDecimal rimWidth, BigDecimal offset, BigDecimal offsetMin, BigDecimal offsetMax, BigDecimal cb, BigDecimal cbMin, BigDecimal cbMax, String lang, String brands, String brandsExclude, String countries, String countriesExclude) throws ApiException {
        com.squareup.okhttp.Call call = boltPatternsReadValidateBeforeCall(boltPattern, rimDiameter, rimWidth, offset, offsetMin, offsetMax, cb, cbMin, cbMax, lang, brands, brandsExclude, countries, countriesExclude, null, null);
        Type localVarReturnType = new TypeToken<List<MakeWithModels>>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Model modifications by bolt pattern (asynchronously)
     * Get a list of model modifications matching to the given bolt pattern
     * @param boltPattern Bolt pattern combines number of stud holes and pitch circle diameter. Use _**&#x60;GET /bolt-patterns/&#x60;**_ to get possible values (e.g. &#x60;5x105&#x60;) (required)
     * @param rimDiameter Rim diameter, in (e.g. &#x60;16&#x60;) (optional)
     * @param rimWidth Rim width, in (e.g. &#x60;7&#x60;) (optional)
     * @param offset Rim offset, mm (e.g. &#x60;40&#x60;) (optional)
     * @param offsetMin Lower bound for rim offset, mm (e.g. &#x60;35&#x60;) (optional)
     * @param offsetMax Upper bound for rim offset, mm (e.g. &#x60;45&#x60;) (optional)
     * @param cb Centre bore value, mm (e.g. &#x60;60&#x60;) (optional)
     * @param cbMin Lower bound for centre bore value, mm (e.g. &#x60;55&#x60;) (optional)
     * @param cbMax Upper bound for centre bore value, mm (e.g. &#x60;65&#x60;) (optional)
     * @param lang Use this parameter anywhere in the API to get *&#x60;name&#x60;* field translation of the following objects: **&#x60;Make&#x60;**, **&#x60;Model&#x60;**, **&#x60;Market&#x60;**. Across the *&#x60;name&#x60;* this objects will have *&#x60;name_en&#x60;* field with original english name. By default &#x60;en&#x60; language is used.  Available languages: &#x60;en,de,ru,es,pt,fr,ja,zh-cn&#x60;. Currently translation works for chinese &#x60;zh-cn&#x60; language only (optional)
     * @param brands Show information only for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;mitsubishi,nissan,toyota&#x60;) (optional)
     * @param brandsExclude Don&#39;t show information for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;geely,great-wall&#x60;) (optional)
     * @param countries Show information for local manufacturers from specified countries only. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;us,gb,jp&#x60;) (optional)
     * @param countriesExclude Don&#39;t show information for local manufacturers from specified countries. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;ru,ua&#x60;) (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call boltPatternsReadAsync(String boltPattern, BigDecimal rimDiameter, BigDecimal rimWidth, BigDecimal offset, BigDecimal offsetMin, BigDecimal offsetMax, BigDecimal cb, BigDecimal cbMin, BigDecimal cbMax, String lang, String brands, String brandsExclude, String countries, String countriesExclude, final ApiCallback<List<MakeWithModels>> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = boltPatternsReadValidateBeforeCall(boltPattern, rimDiameter, rimWidth, offset, offsetMin, offsetMax, cb, cbMin, cbMax, lang, brands, brandsExclude, countries, countriesExclude, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<List<MakeWithModels>>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
