/*
 * Wheel Fitment API
 * The Wheel Fitment API allows for programmatic access to the database of www.wheel-size.com and its services. Use this API to retrieve information about vehicle fitment database for rims and tires, including OE and option fitments, and plus/minus sizing fitment information. A variety of country and language specific options are available. The coverage of fitment data for vehicles manufactured since 2000 is nearly 100%.  The information about fitment data is updated on a daily basis.
 *
 * OpenAPI spec version: v1
 * Contact: info@wheel-size.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.wheelsize.api.client.api;

import com.wheelsize.api.client.ApiCallback;
import com.wheelsize.api.client.ApiClient;
import com.wheelsize.api.client.ApiException;
import com.wheelsize.api.client.ApiResponse;
import com.wheelsize.api.client.Configuration;
import com.wheelsize.api.client.Pair;
import com.wheelsize.api.client.ProgressRequestBody;
import com.wheelsize.api.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import java.math.BigDecimal;
import com.wheelsize.api.client.model.MakeWithModels;
import com.wheelsize.api.client.model.Tire;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TiresApi {
    private ApiClient apiClient;

    public TiresApi() {
        this(Configuration.getDefaultApiClient());
    }

    public TiresApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /**
     * Build call for tiresList
     * @param width Tire width, mm (e.g. &#x60;195&#x60;) (optional)
     * @param widthMin Lower bound for tire width, mm (e.g. &#x60;165&#x60;) (optional)
     * @param widthMax Upper bound for tire width, mm (e.g. &#x60;200&#x60;) (optional)
     * @param aspectRatio Aspect ratio, % (e.g. &#x60;50&#x60;) (optional)
     * @param aspectRatioMin Lower bound for aspect ratio, % (e.g. &#x60;30&#x60;) (optional)
     * @param aspectRatioMax Upper bound for aspect ratio, % (e.g. &#x60;70&#x60;) (optional)
     * @param rimDiameter Rim diameter, in (e.g. &#x60;16&#x60;) (optional)
     * @param rimDiameterMin Lower bound for rim diameter, in (e.g. &#x60;13&#x60;) (optional)
     * @param rimDiameterMax Upper bound for rim diameter, in (e.g. &#x60;20&#x60;) (optional)
     * @param brands Show information only for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;mitsubishi,nissan,toyota&#x60;) (optional)
     * @param brandsExclude Don&#39;t show information for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;geely,great-wall&#x60;) (optional)
     * @param countries Show information for local manufacturers from specified countries only. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;us,gb,jp&#x60;) (optional)
     * @param countriesExclude Don&#39;t show information for local manufacturers from specified countries. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;ru,ua&#x60;) (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call tiresListCall(BigDecimal width, BigDecimal widthMin, BigDecimal widthMax, BigDecimal aspectRatio, BigDecimal aspectRatioMin, BigDecimal aspectRatioMax, BigDecimal rimDiameter, BigDecimal rimDiameterMin, BigDecimal rimDiameterMax, String brands, String brandsExclude, String countries, String countriesExclude, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/tires/";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (width != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("width", width));
        if (widthMin != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("width_min", widthMin));
        if (widthMax != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("width_max", widthMax));
        if (aspectRatio != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("aspect_ratio", aspectRatio));
        if (aspectRatioMin != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("aspect_ratio_min", aspectRatioMin));
        if (aspectRatioMax != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("aspect_ratio_max", aspectRatioMax));
        if (rimDiameter != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("rim_diameter", rimDiameter));
        if (rimDiameterMin != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("rim_diameter_min", rimDiameterMin));
        if (rimDiameterMax != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("rim_diameter_max", rimDiameterMax));
        if (brands != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("brands", brands));
        if (brandsExclude != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("brands_exclude", brandsExclude));
        if (countries != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("countries", countries));
        if (countriesExclude != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("countries_exclude", countriesExclude));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "user_key" };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call tiresListValidateBeforeCall(BigDecimal width, BigDecimal widthMin, BigDecimal widthMax, BigDecimal aspectRatio, BigDecimal aspectRatioMin, BigDecimal aspectRatioMax, BigDecimal rimDiameter, BigDecimal rimDiameterMin, BigDecimal rimDiameterMax, String brands, String brandsExclude, String countries, String countriesExclude, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        

        com.squareup.okhttp.Call call = tiresListCall(width, widthMin, widthMax, aspectRatio, aspectRatioMin, aspectRatioMax, rimDiameter, rimDiameterMin, rimDiameterMax, brands, brandsExclude, countries, countriesExclude, progressListener, progressRequestListener);
        return call;

    }

    /**
     * Returns a list of tires
     * Get a list of tires with a number of matching model modifications
     * @param width Tire width, mm (e.g. &#x60;195&#x60;) (optional)
     * @param widthMin Lower bound for tire width, mm (e.g. &#x60;165&#x60;) (optional)
     * @param widthMax Upper bound for tire width, mm (e.g. &#x60;200&#x60;) (optional)
     * @param aspectRatio Aspect ratio, % (e.g. &#x60;50&#x60;) (optional)
     * @param aspectRatioMin Lower bound for aspect ratio, % (e.g. &#x60;30&#x60;) (optional)
     * @param aspectRatioMax Upper bound for aspect ratio, % (e.g. &#x60;70&#x60;) (optional)
     * @param rimDiameter Rim diameter, in (e.g. &#x60;16&#x60;) (optional)
     * @param rimDiameterMin Lower bound for rim diameter, in (e.g. &#x60;13&#x60;) (optional)
     * @param rimDiameterMax Upper bound for rim diameter, in (e.g. &#x60;20&#x60;) (optional)
     * @param brands Show information only for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;mitsubishi,nissan,toyota&#x60;) (optional)
     * @param brandsExclude Don&#39;t show information for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;geely,great-wall&#x60;) (optional)
     * @param countries Show information for local manufacturers from specified countries only. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;us,gb,jp&#x60;) (optional)
     * @param countriesExclude Don&#39;t show information for local manufacturers from specified countries. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;ru,ua&#x60;) (optional)
     * @return List&lt;Tire&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public List<Tire> tiresList(BigDecimal width, BigDecimal widthMin, BigDecimal widthMax, BigDecimal aspectRatio, BigDecimal aspectRatioMin, BigDecimal aspectRatioMax, BigDecimal rimDiameter, BigDecimal rimDiameterMin, BigDecimal rimDiameterMax, String brands, String brandsExclude, String countries, String countriesExclude) throws ApiException {
        ApiResponse<List<Tire>> resp = tiresListWithHttpInfo(width, widthMin, widthMax, aspectRatio, aspectRatioMin, aspectRatioMax, rimDiameter, rimDiameterMin, rimDiameterMax, brands, brandsExclude, countries, countriesExclude);
        return resp.getData();
    }

    /**
     * Returns a list of tires
     * Get a list of tires with a number of matching model modifications
     * @param width Tire width, mm (e.g. &#x60;195&#x60;) (optional)
     * @param widthMin Lower bound for tire width, mm (e.g. &#x60;165&#x60;) (optional)
     * @param widthMax Upper bound for tire width, mm (e.g. &#x60;200&#x60;) (optional)
     * @param aspectRatio Aspect ratio, % (e.g. &#x60;50&#x60;) (optional)
     * @param aspectRatioMin Lower bound for aspect ratio, % (e.g. &#x60;30&#x60;) (optional)
     * @param aspectRatioMax Upper bound for aspect ratio, % (e.g. &#x60;70&#x60;) (optional)
     * @param rimDiameter Rim diameter, in (e.g. &#x60;16&#x60;) (optional)
     * @param rimDiameterMin Lower bound for rim diameter, in (e.g. &#x60;13&#x60;) (optional)
     * @param rimDiameterMax Upper bound for rim diameter, in (e.g. &#x60;20&#x60;) (optional)
     * @param brands Show information only for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;mitsubishi,nissan,toyota&#x60;) (optional)
     * @param brandsExclude Don&#39;t show information for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;geely,great-wall&#x60;) (optional)
     * @param countries Show information for local manufacturers from specified countries only. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;us,gb,jp&#x60;) (optional)
     * @param countriesExclude Don&#39;t show information for local manufacturers from specified countries. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;ru,ua&#x60;) (optional)
     * @return ApiResponse&lt;List&lt;Tire&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<List<Tire>> tiresListWithHttpInfo(BigDecimal width, BigDecimal widthMin, BigDecimal widthMax, BigDecimal aspectRatio, BigDecimal aspectRatioMin, BigDecimal aspectRatioMax, BigDecimal rimDiameter, BigDecimal rimDiameterMin, BigDecimal rimDiameterMax, String brands, String brandsExclude, String countries, String countriesExclude) throws ApiException {
        com.squareup.okhttp.Call call = tiresListValidateBeforeCall(width, widthMin, widthMax, aspectRatio, aspectRatioMin, aspectRatioMax, rimDiameter, rimDiameterMin, rimDiameterMax, brands, brandsExclude, countries, countriesExclude, null, null);
        Type localVarReturnType = new TypeToken<List<Tire>>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Returns a list of tires (asynchronously)
     * Get a list of tires with a number of matching model modifications
     * @param width Tire width, mm (e.g. &#x60;195&#x60;) (optional)
     * @param widthMin Lower bound for tire width, mm (e.g. &#x60;165&#x60;) (optional)
     * @param widthMax Upper bound for tire width, mm (e.g. &#x60;200&#x60;) (optional)
     * @param aspectRatio Aspect ratio, % (e.g. &#x60;50&#x60;) (optional)
     * @param aspectRatioMin Lower bound for aspect ratio, % (e.g. &#x60;30&#x60;) (optional)
     * @param aspectRatioMax Upper bound for aspect ratio, % (e.g. &#x60;70&#x60;) (optional)
     * @param rimDiameter Rim diameter, in (e.g. &#x60;16&#x60;) (optional)
     * @param rimDiameterMin Lower bound for rim diameter, in (e.g. &#x60;13&#x60;) (optional)
     * @param rimDiameterMax Upper bound for rim diameter, in (e.g. &#x60;20&#x60;) (optional)
     * @param brands Show information only for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;mitsubishi,nissan,toyota&#x60;) (optional)
     * @param brandsExclude Don&#39;t show information for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;geely,great-wall&#x60;) (optional)
     * @param countries Show information for local manufacturers from specified countries only. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;us,gb,jp&#x60;) (optional)
     * @param countriesExclude Don&#39;t show information for local manufacturers from specified countries. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;ru,ua&#x60;) (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call tiresListAsync(BigDecimal width, BigDecimal widthMin, BigDecimal widthMax, BigDecimal aspectRatio, BigDecimal aspectRatioMin, BigDecimal aspectRatioMax, BigDecimal rimDiameter, BigDecimal rimDiameterMin, BigDecimal rimDiameterMax, String brands, String brandsExclude, String countries, String countriesExclude, final ApiCallback<List<Tire>> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = tiresListValidateBeforeCall(width, widthMin, widthMax, aspectRatio, aspectRatioMin, aspectRatioMax, rimDiameter, rimDiameterMin, rimDiameterMax, brands, brandsExclude, countries, countriesExclude, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<List<Tire>>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for tiresRead
     * @param tire Formatted tire size. Use _**&#x60;GET /tires/&#x60;**_ to get possible values (e.g. &#x60;195/50R15&#x60;) (required)
     * @param width Tire width, mm (e.g. &#x60;195&#x60;) (optional)
     * @param widthMin Lower bound for tire width, mm (e.g. &#x60;165&#x60;) (optional)
     * @param widthMax Upper bound for tire width, mm (e.g. &#x60;200&#x60;) (optional)
     * @param aspectRatio Aspect ratio, % (e.g. &#x60;50&#x60;) (optional)
     * @param aspectRatioMin Lower bound for aspect ratio, % (e.g. &#x60;30&#x60;) (optional)
     * @param aspectRatioMax Upper bound for aspect ratio, % (e.g. &#x60;70&#x60;) (optional)
     * @param rimDiameter Rim diameter, in (e.g. &#x60;16&#x60;) (optional)
     * @param rimDiameterMin Lower bound for rim diameter, in (e.g. &#x60;13&#x60;) (optional)
     * @param rimDiameterMax Upper bound for rim diameter, in (e.g. &#x60;20&#x60;) (optional)
     * @param lang Use this parameter anywhere in the API to get *&#x60;name&#x60;* field translation of the following objects: **&#x60;Make&#x60;**, **&#x60;Model&#x60;**, **&#x60;Market&#x60;**. Across the *&#x60;name&#x60;* this objects will have *&#x60;name_en&#x60;* field with original english name. By default &#x60;en&#x60; language is used.  Available languages: &#x60;en,de,ru,es,pt,fr,ja,zh-cn,zh-tw&#x60;. Currently translation works for chinese &#x60;zh-cn&#x60; language only (optional)
     * @param brands Show information only for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;mitsubishi,nissan,toyota&#x60;) (optional)
     * @param brandsExclude Don&#39;t show information for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;geely,great-wall&#x60;) (optional)
     * @param countries Show information for local manufacturers from specified countries only. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;us,gb,jp&#x60;) (optional)
     * @param countriesExclude Don&#39;t show information for local manufacturers from specified countries. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;ru,ua&#x60;) (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call tiresReadCall(String tire, BigDecimal width, BigDecimal widthMin, BigDecimal widthMax, BigDecimal aspectRatio, BigDecimal aspectRatioMin, BigDecimal aspectRatioMax, BigDecimal rimDiameter, BigDecimal rimDiameterMin, BigDecimal rimDiameterMax, String lang, String brands, String brandsExclude, String countries, String countriesExclude, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/tires/{tire}/"
            .replaceAll("\\{" + "tire" + "\\}", apiClient.escapeString(tire.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (width != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("width", width));
        if (widthMin != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("width_min", widthMin));
        if (widthMax != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("width_max", widthMax));
        if (aspectRatio != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("aspect_ratio", aspectRatio));
        if (aspectRatioMin != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("aspect_ratio_min", aspectRatioMin));
        if (aspectRatioMax != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("aspect_ratio_max", aspectRatioMax));
        if (rimDiameter != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("rim_diameter", rimDiameter));
        if (rimDiameterMin != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("rim_diameter_min", rimDiameterMin));
        if (rimDiameterMax != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("rim_diameter_max", rimDiameterMax));
        if (lang != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("lang", lang));
        if (brands != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("brands", brands));
        if (brandsExclude != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("brands_exclude", brandsExclude));
        if (countries != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("countries", countries));
        if (countriesExclude != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("countries_exclude", countriesExclude));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "user_key" };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call tiresReadValidateBeforeCall(String tire, BigDecimal width, BigDecimal widthMin, BigDecimal widthMax, BigDecimal aspectRatio, BigDecimal aspectRatioMin, BigDecimal aspectRatioMax, BigDecimal rimDiameter, BigDecimal rimDiameterMin, BigDecimal rimDiameterMax, String lang, String brands, String brandsExclude, String countries, String countriesExclude, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'tire' is set
        if (tire == null) {
            throw new ApiException("Missing the required parameter 'tire' when calling tiresRead(Async)");
        }
        

        com.squareup.okhttp.Call call = tiresReadCall(tire, width, widthMin, widthMax, aspectRatio, aspectRatioMin, aspectRatioMax, rimDiameter, rimDiameterMin, rimDiameterMax, lang, brands, brandsExclude, countries, countriesExclude, progressListener, progressRequestListener);
        return call;

    }

    /**
     * Model modifications matching given tire
     * Get a list of model modifications by tire
     * @param tire Formatted tire size. Use _**&#x60;GET /tires/&#x60;**_ to get possible values (e.g. &#x60;195/50R15&#x60;) (required)
     * @param width Tire width, mm (e.g. &#x60;195&#x60;) (optional)
     * @param widthMin Lower bound for tire width, mm (e.g. &#x60;165&#x60;) (optional)
     * @param widthMax Upper bound for tire width, mm (e.g. &#x60;200&#x60;) (optional)
     * @param aspectRatio Aspect ratio, % (e.g. &#x60;50&#x60;) (optional)
     * @param aspectRatioMin Lower bound for aspect ratio, % (e.g. &#x60;30&#x60;) (optional)
     * @param aspectRatioMax Upper bound for aspect ratio, % (e.g. &#x60;70&#x60;) (optional)
     * @param rimDiameter Rim diameter, in (e.g. &#x60;16&#x60;) (optional)
     * @param rimDiameterMin Lower bound for rim diameter, in (e.g. &#x60;13&#x60;) (optional)
     * @param rimDiameterMax Upper bound for rim diameter, in (e.g. &#x60;20&#x60;) (optional)
     * @param lang Use this parameter anywhere in the API to get *&#x60;name&#x60;* field translation of the following objects: **&#x60;Make&#x60;**, **&#x60;Model&#x60;**, **&#x60;Market&#x60;**. Across the *&#x60;name&#x60;* this objects will have *&#x60;name_en&#x60;* field with original english name. By default &#x60;en&#x60; language is used.  Available languages: &#x60;en,de,ru,es,pt,fr,ja,zh-cn,zh-tw&#x60;. Currently translation works for chinese &#x60;zh-cn&#x60; language only (optional)
     * @param brands Show information only for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;mitsubishi,nissan,toyota&#x60;) (optional)
     * @param brandsExclude Don&#39;t show information for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;geely,great-wall&#x60;) (optional)
     * @param countries Show information for local manufacturers from specified countries only. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;us,gb,jp&#x60;) (optional)
     * @param countriesExclude Don&#39;t show information for local manufacturers from specified countries. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;ru,ua&#x60;) (optional)
     * @return List&lt;MakeWithModels&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public List<MakeWithModels> tiresRead(String tire, BigDecimal width, BigDecimal widthMin, BigDecimal widthMax, BigDecimal aspectRatio, BigDecimal aspectRatioMin, BigDecimal aspectRatioMax, BigDecimal rimDiameter, BigDecimal rimDiameterMin, BigDecimal rimDiameterMax, String lang, String brands, String brandsExclude, String countries, String countriesExclude) throws ApiException {
        ApiResponse<List<MakeWithModels>> resp = tiresReadWithHttpInfo(tire, width, widthMin, widthMax, aspectRatio, aspectRatioMin, aspectRatioMax, rimDiameter, rimDiameterMin, rimDiameterMax, lang, brands, brandsExclude, countries, countriesExclude);
        return resp.getData();
    }

    /**
     * Model modifications matching given tire
     * Get a list of model modifications by tire
     * @param tire Formatted tire size. Use _**&#x60;GET /tires/&#x60;**_ to get possible values (e.g. &#x60;195/50R15&#x60;) (required)
     * @param width Tire width, mm (e.g. &#x60;195&#x60;) (optional)
     * @param widthMin Lower bound for tire width, mm (e.g. &#x60;165&#x60;) (optional)
     * @param widthMax Upper bound for tire width, mm (e.g. &#x60;200&#x60;) (optional)
     * @param aspectRatio Aspect ratio, % (e.g. &#x60;50&#x60;) (optional)
     * @param aspectRatioMin Lower bound for aspect ratio, % (e.g. &#x60;30&#x60;) (optional)
     * @param aspectRatioMax Upper bound for aspect ratio, % (e.g. &#x60;70&#x60;) (optional)
     * @param rimDiameter Rim diameter, in (e.g. &#x60;16&#x60;) (optional)
     * @param rimDiameterMin Lower bound for rim diameter, in (e.g. &#x60;13&#x60;) (optional)
     * @param rimDiameterMax Upper bound for rim diameter, in (e.g. &#x60;20&#x60;) (optional)
     * @param lang Use this parameter anywhere in the API to get *&#x60;name&#x60;* field translation of the following objects: **&#x60;Make&#x60;**, **&#x60;Model&#x60;**, **&#x60;Market&#x60;**. Across the *&#x60;name&#x60;* this objects will have *&#x60;name_en&#x60;* field with original english name. By default &#x60;en&#x60; language is used.  Available languages: &#x60;en,de,ru,es,pt,fr,ja,zh-cn,zh-tw&#x60;. Currently translation works for chinese &#x60;zh-cn&#x60; language only (optional)
     * @param brands Show information only for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;mitsubishi,nissan,toyota&#x60;) (optional)
     * @param brandsExclude Don&#39;t show information for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;geely,great-wall&#x60;) (optional)
     * @param countries Show information for local manufacturers from specified countries only. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;us,gb,jp&#x60;) (optional)
     * @param countriesExclude Don&#39;t show information for local manufacturers from specified countries. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;ru,ua&#x60;) (optional)
     * @return ApiResponse&lt;List&lt;MakeWithModels&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<List<MakeWithModels>> tiresReadWithHttpInfo(String tire, BigDecimal width, BigDecimal widthMin, BigDecimal widthMax, BigDecimal aspectRatio, BigDecimal aspectRatioMin, BigDecimal aspectRatioMax, BigDecimal rimDiameter, BigDecimal rimDiameterMin, BigDecimal rimDiameterMax, String lang, String brands, String brandsExclude, String countries, String countriesExclude) throws ApiException {
        com.squareup.okhttp.Call call = tiresReadValidateBeforeCall(tire, width, widthMin, widthMax, aspectRatio, aspectRatioMin, aspectRatioMax, rimDiameter, rimDiameterMin, rimDiameterMax, lang, brands, brandsExclude, countries, countriesExclude, null, null);
        Type localVarReturnType = new TypeToken<List<MakeWithModels>>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Model modifications matching given tire (asynchronously)
     * Get a list of model modifications by tire
     * @param tire Formatted tire size. Use _**&#x60;GET /tires/&#x60;**_ to get possible values (e.g. &#x60;195/50R15&#x60;) (required)
     * @param width Tire width, mm (e.g. &#x60;195&#x60;) (optional)
     * @param widthMin Lower bound for tire width, mm (e.g. &#x60;165&#x60;) (optional)
     * @param widthMax Upper bound for tire width, mm (e.g. &#x60;200&#x60;) (optional)
     * @param aspectRatio Aspect ratio, % (e.g. &#x60;50&#x60;) (optional)
     * @param aspectRatioMin Lower bound for aspect ratio, % (e.g. &#x60;30&#x60;) (optional)
     * @param aspectRatioMax Upper bound for aspect ratio, % (e.g. &#x60;70&#x60;) (optional)
     * @param rimDiameter Rim diameter, in (e.g. &#x60;16&#x60;) (optional)
     * @param rimDiameterMin Lower bound for rim diameter, in (e.g. &#x60;13&#x60;) (optional)
     * @param rimDiameterMax Upper bound for rim diameter, in (e.g. &#x60;20&#x60;) (optional)
     * @param lang Use this parameter anywhere in the API to get *&#x60;name&#x60;* field translation of the following objects: **&#x60;Make&#x60;**, **&#x60;Model&#x60;**, **&#x60;Market&#x60;**. Across the *&#x60;name&#x60;* this objects will have *&#x60;name_en&#x60;* field with original english name. By default &#x60;en&#x60; language is used.  Available languages: &#x60;en,de,ru,es,pt,fr,ja,zh-cn,zh-tw&#x60;. Currently translation works for chinese &#x60;zh-cn&#x60; language only (optional)
     * @param brands Show information only for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;mitsubishi,nissan,toyota&#x60;) (optional)
     * @param brandsExclude Don&#39;t show information for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;geely,great-wall&#x60;) (optional)
     * @param countries Show information for local manufacturers from specified countries only. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;us,gb,jp&#x60;) (optional)
     * @param countriesExclude Don&#39;t show information for local manufacturers from specified countries. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;ru,ua&#x60;) (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call tiresReadAsync(String tire, BigDecimal width, BigDecimal widthMin, BigDecimal widthMax, BigDecimal aspectRatio, BigDecimal aspectRatioMin, BigDecimal aspectRatioMax, BigDecimal rimDiameter, BigDecimal rimDiameterMin, BigDecimal rimDiameterMax, String lang, String brands, String brandsExclude, String countries, String countriesExclude, final ApiCallback<List<MakeWithModels>> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = tiresReadValidateBeforeCall(tire, width, widthMin, widthMax, aspectRatio, aspectRatioMin, aspectRatioMax, rimDiameter, rimDiameterMin, rimDiameterMax, lang, brands, brandsExclude, countries, countriesExclude, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<List<MakeWithModels>>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
