/*
 * Wheel Fitment API
 * The Wheel Fitment API allows for programmatic access to the database of www.wheel-size.com and its services. Use this API to retrieve information about vehicle fitment database for rims and tires, including OE and option fitments, and plus/minus sizing fitment information. A variety of country and language specific options are available. The coverage of fitment data for vehicles manufactured since 2000 is nearly 100%.  The information about fitment data is updated on a daily basis.
 *
 * OpenAPI spec version: v1
 * Contact: info@wheel-size.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.wheelsize.api.client.api;

import com.wheelsize.api.client.ApiException;
import com.wheelsize.api.client.model.Make;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MakesApi
 */
@Ignore
public class MakesApiTest {

    private final MakesApi api = new MakesApi();

    
    /**
     * Returns a list of manufacturers
     *
     * Get a list of all manufacturers
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void makesListTest() throws ApiException {
        String lang = null;
        String brands = null;
        String brandsExclude = null;
        String countries = null;
        String countriesExclude = null;
        List<Make> response = api.makesList(lang, brands, brandsExclude, countries, countriesExclude);

        // TODO: test validations
    }
    
}
