/*
 * Wheel Fitment API
 * The Wheel Fitment API allows for programmatic access to the database of www.wheel-size.com and its services. Use this API to retrieve information about vehicle fitment database for rims and tires, including OE and option fitments, and plus/minus sizing fitment information. A variety of country and language specific options are available. The coverage of fitment data for vehicles manufactured since 2000 is nearly 100%.  The information about fitment data is updated on a daily basis.
 *
 * OpenAPI spec version: v1
 * Contact: info@wheel-size.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.wheelsize.api.client.api;

import com.wheelsize.api.client.ApiException;
import com.wheelsize.api.client.model.Model;
import com.wheelsize.api.client.model.ModelWithTires;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ModelsApi
 */
@Ignore
public class ModelsApiTest {

    private final ModelsApi api = new ModelsApi();

    
    /**
     * Returns a list of models by manufacturer
     *
     * Get a list of models that match given manufacturer and year (if present)
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void modelsListTest() throws ApiException {
        String make = null;
        Integer year = null;
        String lang = null;
        List<Model> response = api.modelsList(make, year, lang);

        // TODO: test validations
    }
    
    /**
     * Get more info about model
     *
     * Get the detailed information about model series
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void modelsReadTest() throws ApiException {
        String make = null;
        String slug = null;
        String lang = null;
        ModelWithTires response = api.modelsRead(make, slug, lang);

        // TODO: test validations
    }
    
    /**
     * Get more info about model/year
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void modelsReadYearTest() throws ApiException {
        String make = null;
        String slug = null;
        Integer year = null;
        String lang = null;
        ModelWithTires response = api.modelsReadYear(make, slug, year, lang);

        // TODO: test validations
    }
    
}
