/*
 * Wheel Fitment API
 * The Wheel Fitment API allows for programmatic access to the database of www.wheel-size.com and its services. Use this API to retrieve information about vehicle fitment database for rims and tires, including OE and option fitments, and plus/minus sizing fitment information. A variety of country and language specific options are available. The coverage of fitment data for vehicles manufactured since 2000 is nearly 100%.  The information about fitment data is updated on a daily basis.
 *
 * OpenAPI spec version: v1
 * Contact: info@wheel-size.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.wheelsize.api.client.api;

import com.wheelsize.api.client.ApiException;
import java.math.BigDecimal;
import com.wheelsize.api.client.model.MakeWithModels;
import com.wheelsize.api.client.model.Vehicle;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SearchApi
 */
@Ignore
public class SearchApiTest {

    private final SearchApi api = new SearchApi();

    
    /**
     * Find models matching given high flotation tire
     *
     * Get a list of model modifications that match the given tire size in high flotation sizing system
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchByHfTireListTest() throws ApiException {
        BigDecimal tireDiameter = null;
        BigDecimal tireSectionWidth = null;
        BigDecimal rimDiameterHf = null;
        String lang = null;
        String brands = null;
        String brandsExclude = null;
        String countries = null;
        String countriesExclude = null;
        List<MakeWithModels> response = api.searchByHfTireList(tireDiameter, tireSectionWidth, rimDiameterHf, lang, brands, brandsExclude, countries, countriesExclude);

        // TODO: test validations
    }
    
    /**
     * Find OE and option fitments by model/year/trim
     *
     * Find OE and option fitments that match the given manufacturer, model, year and trim.  **It&#39;s an alias** for _**&#x60;GET /vehicles/&#x60;**_ method
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchByModelListTest() throws ApiException {
        String make = null;
        String model = null;
        Integer year = null;
        String trim = null;
        Boolean onlyOem = null;
        String lang = null;
        List<Vehicle> response = api.searchByModelList(make, model, year, trim, onlyOem, lang);

        // TODO: test validations
    }
    
    /**
     * Find models matching given rim parameters
     *
     * Get a list of model modifications that match the given rim parameters, grouped by manufacturer.  It&#39;s an alias for _**&#x60;GET /bolt-patterns/{bolt_pattern}/&#x60;**_        method with given path and query parameters.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchByRimListTest() throws ApiException {
        String boltPattern = null;
        BigDecimal rimDiameter = null;
        BigDecimal rimWidth = null;
        BigDecimal offset = null;
        BigDecimal offsetMin = null;
        BigDecimal offsetMax = null;
        BigDecimal cb = null;
        BigDecimal cbMin = null;
        BigDecimal cbMax = null;
        String lang = null;
        String brands = null;
        String brandsExclude = null;
        String countries = null;
        String countriesExclude = null;
        List<MakeWithModels> response = api.searchByRimList(boltPattern, rimDiameter, rimWidth, offset, offsetMin, offsetMax, cb, cbMin, cbMax, lang, brands, brandsExclude, countries, countriesExclude);

        // TODO: test validations
    }
    
    /**
     * Find models matching given tire parameters
     *
     * Get a list of model modifications matching given tire, grouped by manufacturer.  It&#39;s an alias for _**&#x60;GET /tire/{tire}/&#x60;**_ method  (tire configuration is combined of required tire width, aspect ratio and rim diameter).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchByTireListTest() throws ApiException {
        BigDecimal tireWidth = null;
        BigDecimal aspectRatio = null;
        BigDecimal rimDiameter = null;
        String lang = null;
        String brands = null;
        String brandsExclude = null;
        String countries = null;
        String countriesExclude = null;
        List<MakeWithModels> response = api.searchByTireList(tireWidth, aspectRatio, rimDiameter, lang, brands, brandsExclude, countries, countriesExclude);

        // TODO: test validations
    }
    
}
