/*
 * Wheel Fitment API
 * The Wheel Fitment API allows for programmatic access to the database of www.wheel-size.com and its services. Use this API to retrieve information about vehicle fitment database for rims and tires, including OE and option fitments, and plus/minus sizing fitment information. A variety of country and language specific options are available. The coverage of fitment data for vehicles manufactured since 2000 is nearly 100%.  The information about fitment data is updated on a daily basis.
 *
 * OpenAPI spec version: v1
 * Contact: info@wheel-size.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.wheelsize.api.client.api;

import com.wheelsize.api.client.ApiException;
import java.math.BigDecimal;
import com.wheelsize.api.client.model.MakeWithModels;
import com.wheelsize.api.client.model.Vehicle;
import org.junit.Test;
import org.junit.Ignore;
import static org.junit.Assert.*;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SearchApi
 */
@Ignore
public class SearchApiTest {

    private final SearchApi api = new SearchApi();

    
    /**
     * Find models matching given high flotation tire
     *
     * Get a list of model modifications that match the given tire size in high flotation sizing system
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchByHfTireListTest() throws ApiException {
        BigDecimal tireDiameter = new BigDecimal(31);
        BigDecimal tireSectionWidth = new BigDecimal(10.5);
        BigDecimal rimDiameterHf = new BigDecimal(15);
        String lang = null;
        String brands = null;
        String brandsExclude = null;
        String countries = null;
        String countriesExclude = null;
        List<MakeWithModels> response = api.searchByHfTireList(tireDiameter, tireSectionWidth, rimDiameterHf, lang, brands, brandsExclude, countries, countriesExclude);

        // TODO: test validations
        assertTrue("Response list should not be empty", response.size() > 0);
    }
    
    /**
     * Find OE and option fitments by model/year/trim
     *
     * Find OE and option fitments that match the given manufacturer, model, year and trim.  **It&#39;s an alias** for _**&#x60;GET /vehicles/&#x60;**_ method
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchByModelListTest() throws ApiException {
        String make = "mitsubishi";
        String model = "outlander";
        Integer year = 2015;
        String trim = null;
        Boolean onlyOem = null;
        String lang = null;
        List<Vehicle> response = api.searchByModelList(make, model, year, null, onlyOem, lang);

        // TODO: test validations
        assertTrue("Response list should not be empty", response.size() > 0);

        trim = "20-gg2w-iii-restyling";
        // trim = response[0]["slug"];
        assertNotNull(trim);

        List<Vehicle> response2 = api.searchByModelList(make, model, year, trim, onlyOem, lang);

        assertTrue("Filtered response list should not be empty", response2.size() > 0);
        assertTrue(response2.size() < response.size());

    }
    
    /**
     * Find models matching given rim parameters
     *
     * Get a list of model modifications that match the given rim parameters, grouped by manufacturer.  It&#39;s an alias for _**&#x60;GET /bolt-patterns/{bolt_pattern}/&#x60;**_        method with given path and query parameters.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchByRimListTest() throws ApiException {
        String boltPattern = "5x100";
        BigDecimal rimDiameter = new BigDecimal(16);
        BigDecimal rimWidth = new BigDecimal(7);
        BigDecimal offset = new BigDecimal(40);
        BigDecimal offsetMin = null;
        BigDecimal offsetMax = null;
        BigDecimal cb = null;
        BigDecimal cbMin = null;
        BigDecimal cbMax = null;
        String lang = null;
        String brands = null;
        String brandsExclude = null;
        String countries = null;
        String countriesExclude = null;
        List<MakeWithModels> response = api.searchByRimList(boltPattern, rimDiameter, rimWidth, null, offsetMin, offsetMax, cb, cbMin, cbMax, lang, brands, brandsExclude, countries, countriesExclude);
        List<MakeWithModels> response2 = api.searchByRimList(boltPattern, rimDiameter, rimWidth, offset, offsetMin, offsetMax, cb, cbMin, cbMax, lang, brands, brandsExclude, countries, countriesExclude);

        // TODO: test validations
        assertTrue("Response list should not be empty", response.size() > 0);
        assertTrue("Filtered response list should not be empty", response2.size() > 0);
        assertTrue(response2.size() < response.size());
    }
    
    /**
     * Find models matching given tire parameters
     *
     * Get a list of model modifications matching given tire, grouped by manufacturer.  It&#39;s an alias for _**&#x60;GET /tire/{tire}/&#x60;**_ method  (tire configuration is combined of required tire width, aspect ratio and rim diameter).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchByTireListTest() throws ApiException {
        BigDecimal tireWidth = new BigDecimal(195);
        BigDecimal aspectRatio = new BigDecimal(50);
        BigDecimal rimDiameter = new BigDecimal(16);
        String lang = null;
        String brands = null;
        String brandsExclude = null;
        String countries = null;
        String countriesExclude = null;
        List<MakeWithModels> response = api.searchByTireList(tireWidth, aspectRatio, rimDiameter, lang, brands, brandsExclude, countries, countriesExclude);
        List<MakeWithModels> response2 = api.searchByTireList(tireWidth, aspectRatio, rimDiameter, lang, "chevrolet", brandsExclude, countries, countriesExclude);

        // TODO: test validations
        assertTrue("Response list should not be empty", response.size() > 0);
        assertTrue("Filtered response list should not be empty", response2.size() > 0);
        assertEquals(response2.size(), 1);
    }
    
}
