/*
 * Wheel Fitment API
 * The Wheel Fitment API allows for programmatic access to the database of www.wheel-size.com and its services. Use this API to retrieve information about vehicle fitment database for rims and tires, including OE and option fitments, and plus/minus sizing fitment information. A variety of country and language specific options are available. The coverage of fitment data for vehicles manufactured since 2000 is nearly 100%.  The information about fitment data is updated on a daily basis.
 *
 * OpenAPI spec version: v1
 * Contact: info@wheel-size.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.wheelsize.api.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * Power in different units (can be __*&#x60;null&#x60;*__)
 */
@ApiModel(description = "Power in different units (can be __*`null`*__)")

public class Power {
  @SerializedName("PS")
  private BigDecimal PS = null;

  @SerializedName("hp")
  private BigDecimal hp = null;

  @SerializedName("kW")
  private BigDecimal kW = null;

  public Power PS(BigDecimal PS) {
    this.PS = PS;
    return this;
  }

   /**
   * Power, PS (e.g. &#x60;169&#x60;)
   * @return PS
  **/
  @ApiModelProperty(required = true, value = "Power, PS (e.g. `169`)")
  public BigDecimal getPS() {
    return PS;
  }

  public void setPS(BigDecimal PS) {
    this.PS = PS;
  }

  public Power hp(BigDecimal hp) {
    this.hp = hp;
    return this;
  }

   /**
   * Power, hp (e.g. &#x60;166&#x60;)
   * @return hp
  **/
  @ApiModelProperty(required = true, value = "Power, hp (e.g. `166`)")
  public BigDecimal getHp() {
    return hp;
  }

  public void setHp(BigDecimal hp) {
    this.hp = hp;
  }

  public Power kW(BigDecimal kW) {
    this.kW = kW;
    return this;
  }

   /**
   * Power, kW (e.g. &#x60;124&#x60;)
   * @return kW
  **/
  @ApiModelProperty(required = true, value = "Power, kW (e.g. `124`)")
  public BigDecimal getKW() {
    return kW;
  }

  public void setKW(BigDecimal kW) {
    this.kW = kW;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Power power = (Power) o;
    return Objects.equals(this.PS, power.PS) &&
        Objects.equals(this.hp, power.hp) &&
        Objects.equals(this.kW, power.kW);
  }

  @Override
  public int hashCode() {
    return Objects.hash(PS, hp, kW);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Power {\n");
    
    sb.append("    PS: ").append(toIndentedString(PS)).append("\n");
    sb.append("    hp: ").append(toIndentedString(hp)).append("\n");
    sb.append("    kW: ").append(toIndentedString(kW)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

