/*
 * Wheel Fitment API
 * The Wheel Fitment API allows for programmatic access to the database of www.wheel-size.com and its services. Use this API to retrieve information about vehicle fitment database for rims and tires, including OE and option fitments, and plus/minus sizing fitment information. A variety of country and language specific options are available. The coverage of fitment data for vehicles manufactured since 2000 is nearly 100%.  The information about fitment data is updated on a daily basis.
 *
 * OpenAPI spec version: v1
 * Contact: info@wheel-size.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.wheelsize.api.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * Tire pressure in different units (can be __*&#x60;null&#x60;*__)
 */
@ApiModel(description = "Tire pressure in different units (can be __*`null`*__)")

public class Pressure {
  @SerializedName("bar")
  private BigDecimal bar = null;

  @SerializedName("psi")
  private BigDecimal psi = null;

  @SerializedName("kPa")
  private BigDecimal kPa = null;

  public Pressure bar(BigDecimal bar) {
    this.bar = bar;
    return this;
  }

   /**
   * Pressure, bar (e.g. &#x60;2.4&#x60;)
   * @return bar
  **/
  @ApiModelProperty(value = "Pressure, bar (e.g. `2.4`)")
  public BigDecimal getBar() {
    return bar;
  }

  public void setBar(BigDecimal bar) {
    this.bar = bar;
  }

  public Pressure psi(BigDecimal psi) {
    this.psi = psi;
    return this;
  }

   /**
   * Pressure, psi (e.g. &#x60;35&#x60;)
   * @return psi
  **/
  @ApiModelProperty(value = "Pressure, psi (e.g. `35`)")
  public BigDecimal getPsi() {
    return psi;
  }

  public void setPsi(BigDecimal psi) {
    this.psi = psi;
  }

  public Pressure kPa(BigDecimal kPa) {
    this.kPa = kPa;
    return this;
  }

   /**
   * Pressure, kPa (e.g. &#x60;240&#x60;)
   * @return kPa
  **/
  @ApiModelProperty(value = "Pressure, kPa (e.g. `240`)")
  public BigDecimal getKPa() {
    return kPa;
  }

  public void setKPa(BigDecimal kPa) {
    this.kPa = kPa;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Pressure pressure = (Pressure) o;
    return Objects.equals(this.bar, pressure.bar) &&
        Objects.equals(this.psi, pressure.psi) &&
        Objects.equals(this.kPa, pressure.kPa);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bar, psi, kPa);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Pressure {\n");
    
    sb.append("    bar: ").append(toIndentedString(bar)).append("\n");
    sb.append("    psi: ").append(toIndentedString(psi)).append("\n");
    sb.append("    kPa: ").append(toIndentedString(kPa)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

