/*
 * Wheel Fitment API
 * The Wheel Fitment API allows for programmatic access to the database of www.wheel-size.com and its services. Use this API to retrieve information about vehicle fitment database for rims and tires, including OE and option fitments, and plus/minus sizing fitment information. A variety of country and language specific options are available. The coverage of fitment data for vehicles manufactured since 2000 is nearly 100%.  The information about fitment data is updated on a daily basis.
 *
 * OpenAPI spec version: v1
 * Contact: info@wheel-size.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.wheelsize.api.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.wheelsize.api.client.model.Aggregation;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Rim diameter, offset, and width values aggregated by bolt pattern
 */
@ApiModel(description = "Rim diameter, offset, and width values aggregated by bolt pattern")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-17T19:57:08.897+06:00")
public class RimAgregation {
  @SerializedName("diameter")
  private Aggregation diameter = null;

  @SerializedName("offset")
  private Aggregation offset = null;

  @SerializedName("width")
  private Aggregation width = null;

  public RimAgregation diameter(Aggregation diameter) {
    this.diameter = diameter;
    return this;
  }

   /**
   * Get diameter
   * @return diameter
  **/
  @ApiModelProperty(required = true, value = "")
  public Aggregation getDiameter() {
    return diameter;
  }

  public void setDiameter(Aggregation diameter) {
    this.diameter = diameter;
  }

  public RimAgregation offset(Aggregation offset) {
    this.offset = offset;
    return this;
  }

   /**
   * Get offset
   * @return offset
  **/
  @ApiModelProperty(required = true, value = "")
  public Aggregation getOffset() {
    return offset;
  }

  public void setOffset(Aggregation offset) {
    this.offset = offset;
  }

  public RimAgregation width(Aggregation width) {
    this.width = width;
    return this;
  }

   /**
   * Get width
   * @return width
  **/
  @ApiModelProperty(required = true, value = "")
  public Aggregation getWidth() {
    return width;
  }

  public void setWidth(Aggregation width) {
    this.width = width;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RimAgregation rimAgregation = (RimAgregation) o;
    return Objects.equals(this.diameter, rimAgregation.diameter) &&
        Objects.equals(this.offset, rimAgregation.offset) &&
        Objects.equals(this.width, rimAgregation.width);
  }

  @Override
  public int hashCode() {
    return Objects.hash(diameter, offset, width);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RimAgregation {\n");
    
    sb.append("    diameter: ").append(toIndentedString(diameter)).append("\n");
    sb.append("    offset: ").append(toIndentedString(offset)).append("\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

