/*
 * Wheel Fitment API
 * The Wheel Fitment API allows for programmatic access to the database of www.wheel-size.com and its services. Use this API to retrieve information about vehicle fitment database for rims and tires, including OE and option fitments, and plus/minus sizing fitment information. A variety of country and language specific options are available. The coverage of fitment data for vehicles manufactured since 2000 is nearly 100%.  The information about fitment data is updated on a daily basis.
 *
 * OpenAPI spec version: v1
 * Contact: info@wheel-size.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.wheelsize.api.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.wheelsize.api.client.model.Aggregation;
import com.wheelsize.api.client.model.SizeAggregation;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Tire width, aspect ratio, and rim diameter values aggregated by all possible model modifications
 */
@ApiModel(description = "Tire width, aspect ratio, and rim diameter values aggregated by all possible model modifications")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-17T19:57:08.897+06:00")
public class TiresAggregation {
  @SerializedName("aspect_ratio")
  private Aggregation aspectRatio = null;

  @SerializedName("diameter")
  private Aggregation diameter = null;

  @SerializedName("width")
  private Aggregation width = null;

  @SerializedName("tire_size")
  private SizeAggregation tireSize = null;

  public TiresAggregation aspectRatio(Aggregation aspectRatio) {
    this.aspectRatio = aspectRatio;
    return this;
  }

   /**
   * Get aspectRatio
   * @return aspectRatio
  **/
  @ApiModelProperty(required = true, value = "")
  public Aggregation getAspectRatio() {
    return aspectRatio;
  }

  public void setAspectRatio(Aggregation aspectRatio) {
    this.aspectRatio = aspectRatio;
  }

  public TiresAggregation diameter(Aggregation diameter) {
    this.diameter = diameter;
    return this;
  }

   /**
   * Get diameter
   * @return diameter
  **/
  @ApiModelProperty(required = true, value = "")
  public Aggregation getDiameter() {
    return diameter;
  }

  public void setDiameter(Aggregation diameter) {
    this.diameter = diameter;
  }

  public TiresAggregation width(Aggregation width) {
    this.width = width;
    return this;
  }

   /**
   * Get width
   * @return width
  **/
  @ApiModelProperty(required = true, value = "")
  public Aggregation getWidth() {
    return width;
  }

  public void setWidth(Aggregation width) {
    this.width = width;
  }

  public TiresAggregation tireSize(SizeAggregation tireSize) {
    this.tireSize = tireSize;
    return this;
  }

   /**
   * Get tireSize
   * @return tireSize
  **/
  @ApiModelProperty(required = true, value = "")
  public SizeAggregation getTireSize() {
    return tireSize;
  }

  public void setTireSize(SizeAggregation tireSize) {
    this.tireSize = tireSize;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TiresAggregation tiresAggregation = (TiresAggregation) o;
    return Objects.equals(this.aspectRatio, tiresAggregation.aspectRatio) &&
        Objects.equals(this.diameter, tiresAggregation.diameter) &&
        Objects.equals(this.width, tiresAggregation.width) &&
        Objects.equals(this.tireSize, tiresAggregation.tireSize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(aspectRatio, diameter, width, tireSize);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TiresAggregation {\n");
    
    sb.append("    aspectRatio: ").append(toIndentedString(aspectRatio)).append("\n");
    sb.append("    diameter: ").append(toIndentedString(diameter)).append("\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("    tireSize: ").append(toIndentedString(tireSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

