/*
 * Wheel Fitment API
 * The Wheel Fitment API allows for programmatic access to the database of www.wheel-size.com and its services. Use this API to retrieve information about vehicle fitment database for rims and tires, including OE and option fitments, and plus/minus sizing fitment information. A variety of country and language specific options are available. The coverage of fitment data for vehicles manufactured since 2000 is nearly 100%.  The information about fitment data is updated on a daily basis.
 *
 * OpenAPI spec version: v1
 * Contact: info@wheel-size.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.wheelsize.api.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.wheelsize.api.client.model.Market;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * TrimWithMarketAndYears
 */

public class TrimWithMarketAndYears {
  @SerializedName("trim")
  private String trim = null;

  @SerializedName("market")
  private Market market = null;

  @SerializedName("years")
  private List<Integer> years = null;

  public TrimWithMarketAndYears trim(String trim) {
    this.trim = trim;
    return this;
  }

   /**
   * Trim name (e.g. &#x60;2.0&#x60;, can be __*&#x60;null&#x60;*__)
   * @return trim
  **/
  @ApiModelProperty(value = "Trim name (e.g. `2.0`, can be __*`null`*__)")
  public String getTrim() {
    return trim;
  }

  public void setTrim(String trim) {
    this.trim = trim;
  }

  public TrimWithMarketAndYears market(Market market) {
    this.market = market;
    return this;
  }

   /**
   * Get market
   * @return market
  **/
  @ApiModelProperty(value = "")
  public Market getMarket() {
    return market;
  }

  public void setMarket(Market market) {
    this.market = market;
  }

  public TrimWithMarketAndYears years(List<Integer> years) {
    this.years = years;
    return this;
  }

  public TrimWithMarketAndYears addYearsItem(Integer yearsItem) {
    if (this.years == null) {
      this.years = new ArrayList<Integer>();
    }
    this.years.add(yearsItem);
    return this;
  }

   /**
   * Production years for these trim and market
   * @return years
  **/
  @ApiModelProperty(value = "Production years for these trim and market")
  public List<Integer> getYears() {
    return years;
  }

  public void setYears(List<Integer> years) {
    this.years = years;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TrimWithMarketAndYears trimWithMarketAndYears = (TrimWithMarketAndYears) o;
    return Objects.equals(this.trim, trimWithMarketAndYears.trim) &&
        Objects.equals(this.market, trimWithMarketAndYears.market) &&
        Objects.equals(this.years, trimWithMarketAndYears.years);
  }

  @Override
  public int hashCode() {
    return Objects.hash(trim, market, years);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TrimWithMarketAndYears {\n");
    
    sb.append("    trim: ").append(toIndentedString(trim)).append("\n");
    sb.append("    market: ").append(toIndentedString(market)).append("\n");
    sb.append("    years: ").append(toIndentedString(years)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

