/*
 * Wheel Fitment API
 * The Wheel Fitment API allows for programmatic access to the database of www.wheel-size.com and its services. Use this API to retrieve information about vehicle fitment database for rims and tires, including OE and option fitments, and plus/minus sizing fitment information. A variety of country and language specific options are available. The coverage of fitment data for vehicles manufactured since 2000 is nearly 100%.  The information about fitment data is updated on a daily basis.
 *
 * OpenAPI spec version: v1
 * Contact: info@wheel-size.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.wheelsize.api.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.wheelsize.api.client.model.Market;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Trim
 */

public class Trim {
  @SerializedName("slug")
  private String slug = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("trim")
  private String trim = null;

  @SerializedName("body")
  private String body = null;

  @SerializedName("generation")
  private String generation = null;

  @SerializedName("production_start_year")
  private Integer productionStartYear = null;

  @SerializedName("production_end_year")
  private Integer productionEndYear = null;

  @SerializedName("markets")
  private List<Market> markets = null;

  public Trim slug(String slug) {
    this.slug = slug;
    return this;
  }

   /**
   * Combined trim, body, and generation identifier. Non-unique through markets (e.g. &#x60;20-gg2w-iii-restyling&#x60;)
   * @return slug
  **/
  @ApiModelProperty(value = "Combined trim, body, and generation identifier. Non-unique through markets (e.g. `20-gg2w-iii-restyling`)")
  public String getSlug() {
    return slug;
  }

  public void setSlug(String slug) {
    this.slug = slug;
  }

  public Trim name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Format: __*&#x60;trim (body) [generation]&#x60;*__ (e.g. &#x60;2.0 (GG2W) [III Restyling]&#x60;)
   * @return name
  **/
  @ApiModelProperty(value = "Format: __*`trim (body) [generation]`*__ (e.g. `2.0 (GG2W) [III Restyling]`)")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Trim trim(String trim) {
    this.trim = trim;
    return this;
  }

   /**
   * Trim name. It can be empty for models created for JDM market (e.g. &#x60;2.0&#x60;, can be __*&#x60;null&#x60;*__)
   * @return trim
  **/
  @ApiModelProperty(value = "Trim name. It can be empty for models created for JDM market (e.g. `2.0`, can be __*`null`*__)")
  public String getTrim() {
    return trim;
  }

  public void setTrim(String trim) {
    this.trim = trim;
  }

  public Trim body(String body) {
    this.body = body;
    return this;
  }

   /**
   * Body name. Used extensively for JDM market (e.g. &#x60;GG2W&#x60;, can be __*&#x60;null&#x60;*__)
   * @return body
  **/
  @ApiModelProperty(value = "Body name. Used extensively for JDM market (e.g. `GG2W`, can be __*`null`*__)")
  public String getBody() {
    return body;
  }

  public void setBody(String body) {
    this.body = body;
  }

  public Trim generation(String generation) {
    this.generation = generation;
    return this;
  }

   /**
   * Generation name (e.g. &#x60;III Restyling&#x60;, can be __*&#x60;null&#x60;*__)
   * @return generation
  **/
  @ApiModelProperty(value = "Generation name (e.g. `III Restyling`, can be __*`null`*__)")
  public String getGeneration() {
    return generation;
  }

  public void setGeneration(String generation) {
    this.generation = generation;
  }

  public Trim productionStartYear(Integer productionStartYear) {
    this.productionStartYear = productionStartYear;
    return this;
  }

   /**
   * Trim production start year (e.g. &#x60;2015&#x60;, can be __*&#x60;null&#x60;*__)
   * @return productionStartYear
  **/
  @ApiModelProperty(value = "Trim production start year (e.g. `2015`, can be __*`null`*__)")
  public Integer getProductionStartYear() {
    return productionStartYear;
  }

  public void setProductionStartYear(Integer productionStartYear) {
    this.productionStartYear = productionStartYear;
  }

  public Trim productionEndYear(Integer productionEndYear) {
    this.productionEndYear = productionEndYear;
    return this;
  }

   /**
   * Trim production end year (e.g. &#x60;2016&#x60;, can be __*&#x60;null&#x60;*__)
   * @return productionEndYear
  **/
  @ApiModelProperty(value = "Trim production end year (e.g. `2016`, can be __*`null`*__)")
  public Integer getProductionEndYear() {
    return productionEndYear;
  }

  public void setProductionEndYear(Integer productionEndYear) {
    this.productionEndYear = productionEndYear;
  }

  public Trim markets(List<Market> markets) {
    this.markets = markets;
    return this;
  }

  public Trim addMarketsItem(Market marketsItem) {
    if (this.markets == null) {
      this.markets = new ArrayList<Market>();
    }
    this.markets.add(marketsItem);
    return this;
  }

   /**
   * List of markets where this trim if present
   * @return markets
  **/
  @ApiModelProperty(value = "List of markets where this trim if present")
  public List<Market> getMarkets() {
    return markets;
  }

  public void setMarkets(List<Market> markets) {
    this.markets = markets;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Trim trim = (Trim) o;
    return Objects.equals(this.slug, trim.slug) &&
        Objects.equals(this.name, trim.name) &&
        Objects.equals(this.trim, trim.trim) &&
        Objects.equals(this.body, trim.body) &&
        Objects.equals(this.generation, trim.generation) &&
        Objects.equals(this.productionStartYear, trim.productionStartYear) &&
        Objects.equals(this.productionEndYear, trim.productionEndYear) &&
        Objects.equals(this.markets, trim.markets);
  }

  @Override
  public int hashCode() {
    return Objects.hash(slug, name, trim, body, generation, productionStartYear, productionEndYear, markets);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Trim {\n");
    
    sb.append("    slug: ").append(toIndentedString(slug)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    trim: ").append(toIndentedString(trim)).append("\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    generation: ").append(toIndentedString(generation)).append("\n");
    sb.append("    productionStartYear: ").append(toIndentedString(productionStartYear)).append("\n");
    sb.append("    productionEndYear: ").append(toIndentedString(productionEndYear)).append("\n");
    sb.append("    markets: ").append(toIndentedString(markets)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

