/*
 * Wheel Fitment API
 * The Wheel Fitment API allows for programmatic access to the database of www.wheel-size.com and its services. Use this API to retrieve information about vehicle fitment database for rims and tires, including OE and option fitments, and plus/minus sizing fitment information. A variety of country and language specific options are available. The coverage of fitment data for vehicles manufactured since 2000 is nearly 100%.  The information about fitment data is updated on a daily basis.
 *
 * OpenAPI spec version: v1
 * Contact: info@wheel-size.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.wheelsize.api.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Trim
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-17T19:57:08.897+06:00")
public class Trim {
  @SerializedName("slug")
  private String slug = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("trim")
  private String trim = null;

  @SerializedName("body")
  private String body = null;

  @SerializedName("generation")
  private String generation = null;

  public Trim slug(String slug) {
    this.slug = slug;
    return this;
  }

   /**
   * Combines trim and body name. Format: __*&#x60;trim+body&#x60;*__ if both values provided, otherwise non-empty of them. (e.g. &#x60;2.0+GG2W&#x60;)
   * @return slug
  **/
  @ApiModelProperty(value = "Combines trim and body name. Format: __*`trim+body`*__ if both values provided, otherwise non-empty of them. (e.g. `2.0+GG2W`)")
  public String getSlug() {
    return slug;
  }

  public void setSlug(String slug) {
    this.slug = slug;
  }

  public Trim name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Format: __*&#x60;trim (body)&#x60;*__ if both values provided, otherwise non-empty of them. (e.g. &#x60;2.0 (GG2W)&#x60;)
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Format: __*`trim (body)`*__ if both values provided, otherwise non-empty of them. (e.g. `2.0 (GG2W)`)")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Trim trim(String trim) {
    this.trim = trim;
    return this;
  }

   /**
   * Trim name. It can be empty for models created for JDM market (e.g. &#x60;2.0&#x60;, can be __*&#x60;null&#x60;*__)
   * @return trim
  **/
  @ApiModelProperty(required = true, value = "Trim name. It can be empty for models created for JDM market (e.g. `2.0`, can be __*`null`*__)")
  public String getTrim() {
    return trim;
  }

  public void setTrim(String trim) {
    this.trim = trim;
  }

  public Trim body(String body) {
    this.body = body;
    return this;
  }

   /**
   * Body name. Used extensively for JDM market (e.g. &#x60;GG2W&#x60;, can be __*&#x60;null&#x60;*__)
   * @return body
  **/
  @ApiModelProperty(required = true, value = "Body name. Used extensively for JDM market (e.g. `GG2W`, can be __*`null`*__)")
  public String getBody() {
    return body;
  }

  public void setBody(String body) {
    this.body = body;
  }

  public Trim generation(String generation) {
    this.generation = generation;
    return this;
  }

   /**
   * Generation name (e.g. &#x60;III Restyling&#x60;, can be __*&#x60;null&#x60;*__)
   * @return generation
  **/
  @ApiModelProperty(value = "Generation name (e.g. `III Restyling`, can be __*`null`*__)")
  public String getGeneration() {
    return generation;
  }

  public void setGeneration(String generation) {
    this.generation = generation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Trim trim = (Trim) o;
    return Objects.equals(this.slug, trim.slug) &&
        Objects.equals(this.name, trim.name) &&
        Objects.equals(this.trim, trim.trim) &&
        Objects.equals(this.body, trim.body) &&
        Objects.equals(this.generation, trim.generation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(slug, name, trim, body, generation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Trim {\n");
    
    sb.append("    slug: ").append(toIndentedString(slug)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    trim: ").append(toIndentedString(trim)).append("\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    generation: ").append(toIndentedString(generation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

